ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}

# It's possible we're missing some dependencies for the packages we're testing! This could be improved.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libc-dev build-essential gfortran libopenblas-dev liblapack-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# pyenv setup from https://gist.github.com/jprjr/7667947?permalink_comment_id=3684823#gistcomment-3684823
ENV PYENV_ROOT=/root/.pyenv
ENV PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
RUN set -ex && \
    curl https://pyenv.run | bash && \
    pyenv update && \
    pyenv install ${PYTHON_VERSION}t && \
    pyenv global ${PYTHON_VERSION}t && \
    pyenv rehash

COPY requirements.txt ./
RUN python -m pip install -r requirements.txt

COPY *.py ./
COPY specific_tests/ ./specific_tests/
COPY tested_packages.toml ./

ENTRYPOINT [ "python", "runner.py", "freethreading" ]
