ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}

COPY requirements.txt ./
RUN python -m pip install -r requirements.txt

COPY *.py ./
COPY specific_tests/ ./specific_tests/
COPY tested_packages.toml ./

ENTRYPOINT [ "python", "runner.py", "subinterpreters" ]
