packages = [
    # Top 300 from https://github.com/hugovk/top-pypi-packages
    { name = "boto3" },
    { name = "urllib3" },
    { name = "botocore" },
    { name = "requests" },
    { name = "setuptools" },
    { name = "certifi" },
    { name = "idna" },
    { name = "charset-normalizer" },
    { name = "typing-extensions" },
    { name = "python-dateutil" },
    { name = "s3transfer" },
    { name = "packaging" },
    { name = "grpcio-status" },
    { name = "aiobotocore" },
    { name = "six" },
    { name = "pyyaml" },
    { name = "numpy" },
    { name = "s3fs" },
    { name = "fsspec" },
    { name = "cryptography" },
    { name = "importlib-metadata" },
    { name = "pip" },
    { name = "cffi" },
    { name = "pandas" },
    { name = "zipp" },
    { name = "pydantic" },
    { name = "google-api-core" },
    { name = "pycparser" },
    { name = "wheel" },
    { name = "jmespath" },
    { name = "attrs" },
    { name = "protobuf" },
    { name = "rsa" },
    { name = "click" },
    { name = "pyasn1" },
    { name = "awscli" },
    { name = "platformdirs" },
    { name = "pytz" },
    { name = "colorama" },
    { name = "jinja2" },
    { name = "markupsafe" },
    { name = "pyjwt" },
    { name = "googleapis-common-protos" },
    { name = "tomli" },
    { name = "filelock" },
    { name = "pydantic-core" },
    { name = "cachetools" },
    { name = "wrapt" },
    { name = "google-auth" },
    { name = "virtualenv" },
    { name = "pluggy" },
    { name = "pytest" },
    { name = "docutils" },
    { name = "pyarrow" },
    { name = "pyparsing" },
    { name = "pyasn1-modules" },
    { name = "requests-oauthlib" },
    { name = "aiohttp" },
    { name = "sqlalchemy" },
    { name = "oauthlib" },
    { name = "iniconfig" },
    { name = "annotated-types" },
    { name = "jsonschema" },
    { name = "exceptiongroup" },
    { name = "yarl" },
    { name = "scipy" },
    { name = "multidict" },
    { name = "tzdata" },
    { name = "soupsieve" },
    { name = "greenlet" },
    { name = "isodate" },
    { name = "pygments" },
    { name = "beautifulsoup4" },
    { name = "psutil" },
    { name = "pillow" },
    { name = "frozenlist" },
    { name = "decorator" },
    { name = "pyopenssl" },
    { name = "aiosignal" },
    { name = "tomlkit" },
    { name = "requests-toolbelt" },
    { name = "async-timeout" },
    { name = "tqdm" },
    { name = "distlib" },
    { name = "openpyxl" },
    { name = "more-itertools" },
    { name = "grpcio" },
    { name = "et-xmlfile" },
    { name = "h11" },
    { name = "deprecated" },
    { name = "sniffio" },
    { name = "lxml" },
    { name = "anyio" },
    { name = "pynacl" },
    { name = "proto-plus" },
    { name = "werkzeug" },
    { name = "asn1crypto" },
    { name = "google-cloud-storage" },
    { name = "azure-core" },
    { name = "coverage" },
    { name = "websocket-client" },
    { name = "msgpack" },
    { name = "mypy-extensions" },
    { name = "rich" },
    { name = "pexpect" },
    { name = "importlib-resources" },
    { name = "sortedcontainers" },
    { name = "ptyprocess" },
    { name = "chardet" },
    { name = "grpcio-tools" },
    { name = "cloudpickle" },
    { name = "tenacity" },
    { name = "dill" },
    { name = "aiohappyeyeballs" },
    { name = "httpx" },
    { name = "rpds-py" },
    { name = "poetry-core" },
    { name = "referencing" },
    { name = "flask" },
    { name = "matplotlib" },
    { name = "google-cloud-core" },
    { name = "python-dotenv" },
    { name = "msal" },
    { name = "httpcore" },
    { name = "jsonschema-specifications" },
    { name = "psycopg2-binary" },
    { name = "markdown-it-py" },
    { name = "keyring" },
    { name = "bcrypt" },
    { name = "google-resumable-media" },
    { name = "poetry-plugin-export" },
    { name = "mdurl" },
    { name = "scikit-learn" },
    { name = "pkginfo" },
    { name = "pathspec" },
    { name = "snowflake-connector-python" },
    { name = "paramiko" },
    { name = "tabulate" },
    { name = "gitpython" },
    { name = "networkx" },
    { name = "regex" },
    { name = "kiwisolver" },
    { name = "jaraco-classes", importable_name = "jaraco.classes"},
    { name = "smmap" },
    { name = "gitdb" },
    { name = "jeepney" },
    { name = "secretstorage" },
    { name = "wcwidth" },
    { name = "build" },
    { name = "backoff" },
    { name = "shellingham" },
    { name = "ruamel-yaml", importable_name = "ruamel.yaml" },
    { name = "typedload" },
    { name = "xmltodict" },
    { name = "cycler" },
    { name = "portalocker" },
    { name = "itsdangerous" },
    { name = "py" },
    { name = "google-crc32c" },
    { name = "rapidfuzz" },
    { name = "threadpoolctl" },
    { name = "pyproject-hooks" },
    { name = "pyzmq" },
    { name = "awswrangler" },
    { name = "google-cloud-bigquery" },
    { name = "sqlparse" },
    { name = "fastjsonschema" },
    { name = "py4j" },
    { name = "azure-storage-blob" },
    { name = "msal-extensions" },
    { name = "pytest-cov" },
    { name = "trove-classifiers" },
    { name = "termcolor" },
    { name = "mccabe" },
    { name = "joblib" },
    { name = "google-api-python-client" },
    { name = "google-auth-oauthlib" },
    { name = "fastapi" },
    { name = "pycodestyle" },
    { name = "azure-identity" },
    { name = "fonttools" },
    { name = "ruamel-yaml-clib", importable_name = "ruamel.yaml.clib" },
    { name = "cachecontrol" },
    { name = "marshmallow" },
    { name = "alembic" },
    { name = "tzlocal" },
    { name = "docker" },
    { name = "pymysql" },
    { name = "distro" },
    { name = "prompt-toolkit" },
    { name = "cython" },
    { name = "starlette" },
    { name = "redis" },
    { name = "uritemplate" },
    { name = "poetry" },
    { name = "httplib2" },
    { name = "isort" },
    { name = "ply" },
    { name = "google-auth-httplib2" },
    { name = "defusedxml" },
    { name = "blinker" },
    { name = "dnspython" },
    { name = "uvicorn" },
    { name = "dulwich" },
    { name = "crashtest" },
    { name = "pyrsistent" },
    { name = "toml" },
    { name = "cleo" },
    { name = "scramp" },
    { name = "nest-asyncio" },
    { name = "gunicorn" },
    { name = "markdown" },
    { name = "babel" },
    { name = "installer" },
    { name = "msrest" },
    { name = "huggingface-hub" },
    { name = "opentelemetry-api" },
    { name = "azure-common" },
    { name = "grpc-google-iam-v1" },
    { name = "ipython" },
    { name = "traitlets" },
    { name = "black" },
    { name = "pycryptodomex" },
    { name = "types-requests" },
    { name = "pycryptodome" },
    { name = "future" },
    { name = "setuptools-scm" },
    { name = "mock" },
    { name = "contourpy" },
    { name = "sentry-sdk" },
    { name = "pyflakes" },
    { name = "pendulum" },
    { name = "requests-aws4auth" },
    { name = "tornado" },
    { name = "prometheus-client" },
    { name = "multiprocess" },
    { name = "pygithub" },
    { name = "webencodings" },
    { name = "typing-inspect" },
    { name = "jedi" },
    { name = "parso" },
    { name = "jsonpointer" },
    { name = "flake8" },
    { name = "kubernetes" },
    { name = "mako" },
    { name = "openai" },
    { name = "matplotlib-inline" },
    { name = "loguru" },
    { name = "argcomplete" },
    { name = "transformers" },
    { name = "datadog" },
    { name = "redshift-connector" },
    { name = "pytest-runner" },
    { name = "retry" },
    # { name = "bs4" },  # dummy package
    { name = "pg8000" },
    { name = "sagemaker" },
    { name = "opentelemetry-sdk" },
    { name = "asgiref" },
    { name = "pymongo" },
    { name = "jsonpath-ng" },
    { name = "python-json-logger" },
    { name = "opentelemetry-semantic-conventions" },
    { name = "imageio" },
    { name = "typer" },
    { name = "aioitertools" },
    { name = "pyspark" },
    { name = "zope-interface", importable_name = "zope.interface" },
    { name = "executing" },
    { name = "gym-notices" },
    { name = "websockets" },
    { name = "pkgutil-resolve-name" },
    { name = "debugpy" },
    { name = "apache-airflow" },
    { name = "smart-open" },
    { name = "asttokens" },
    { name = "shapely" },
    { name = "pytzdata" },
    { name = "humanfriendly" },
    { name = "snowflake-sqlalchemy" },
    { name = "arrow" },
    { name = "elasticsearch" },
    { name = "torch" },
    { name = "stack-data" },
    { name = "oscrypto" },
    { name = "pysocks" },
    { name = "pure-eval" },
    { name = "typeguard" },
    { name = "google-cloud-secret-manager" },
    { name = "requests-file" },
    { name = "google-cloud-pubsub" },
    { name = "tokenizers" },
    { name = "sphinx" },
    { name = "jsonpatch" },
    { name = "tb-nightly" },
    { name = "mysql-connector-python" },
    { name = "adal" },
    { name = "pylint" },
    { name = "sympy" },
    { name = "jupyter-core" },
    # Some extras I'm interested in
    { name = "msgspec" },
    { name = "orjson" },
    { name = "ujson" },
    { name = "pika" },
]
